export type ConfigResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: CloudflareConfigError };

export type CloudflareConfigError = {
  code: "invalid_enum" | "invalid_url" | "missing_required_env";
  message: string;
  env?: string;
  value?: string;
  allowed?: readonly string[];
};

export type HunsuDeployTarget = "local" | "dev" | "production";

export type HubCloudflareConfig = {
  target: HunsuDeployTarget;
  workerName: string;
  workerMain: string;
  compatibilityDate: string;
  compatibilityFlags: string[];
  originName: string;
  publicHubApiUrl: string;
  d1DatabaseName: string;
  d1DatabaseId: string;
  r2BucketName: string;
  publishQueueName?: string;
};

export type HubApiWorkerRuntimeConfig = {
  originName: string;
  publicHubApiUrl?: string;
  adminToken?: string;
};

export type HubApiWorkerRuntimeEnv = {
  HUNSU_HUB_ORIGIN_NAME?: string;
  HUNSU_HUB_PUBLIC_API_URL?: string;
  HUNSU_HUB_ADMIN_TOKEN?: string;
};

export type Env = Record<string, string | undefined>;

export const HUNSU_DEPLOY_TARGETS = ["local", "dev", "production"] as const;
export const HUB_WRANGLER_GENERATED_CONFIG_PATH = ".wrangler/generated.toml";
export const HUB_WORKER_MAIN = "../src/index.ts";
export const HUB_WORKER_COMPATIBILITY_DATE = "2026-06-25";
export const HUB_WORKER_COMPATIBILITY_FLAGS = ["nodejs_compat"] as const;

const LOCAL_HUB_DEFAULTS = {
  HUNSU_HUB_WORKER_NAME: "hunsu-hub-api-local",
  HUNSU_HUB_ORIGIN_NAME: "hunsu-local",
  HUNSU_HUB_PUBLIC_API_URL: "http://127.0.0.1:8787",
  HUNSU_HUB_D1_DATABASE_NAME: "hunsu_hub_local",
  HUNSU_HUB_D1_DATABASE_ID: "hunsu-hub-local",
  HUNSU_HUB_R2_BUCKET_NAME: "hunsu-hub-packages-local"
} as const;

export function resolveHubCloudflareConfig(env: Env): ConfigResult<HubCloudflareConfig> {
  return flatMapConfigResult(readDeployTarget(env), target =>
    flatMapConfigResult(readRequiredString(env, "HUNSU_HUB_WORKER_NAME", target), workerName =>
      flatMapConfigResult(readRequiredString(env, "HUNSU_HUB_ORIGIN_NAME", target), originName =>
        flatMapConfigResult(readRequiredUrl(env, "HUNSU_HUB_PUBLIC_API_URL", target), publicHubApiUrl =>
          flatMapConfigResult(readRequiredString(env, "HUNSU_HUB_D1_DATABASE_NAME", target), d1DatabaseName =>
            flatMapConfigResult(readRequiredString(env, "HUNSU_HUB_D1_DATABASE_ID", target), d1DatabaseId =>
              mapConfigResult(readRequiredString(env, "HUNSU_HUB_R2_BUCKET_NAME", target), r2BucketName => ({
                target,
                workerName,
                workerMain: HUB_WORKER_MAIN,
                compatibilityDate: HUB_WORKER_COMPATIBILITY_DATE,
                compatibilityFlags: [...HUB_WORKER_COMPATIBILITY_FLAGS],
                originName,
                publicHubApiUrl,
                d1DatabaseName,
                d1DatabaseId,
                r2BucketName,
                publishQueueName: readOptionalString(env, "HUNSU_HUB_PUBLISH_QUEUE_NAME")
              }))
            )
          )
        )
      )
    )
  );
}

export function resolveHubApiWorkerRuntimeConfig(env: HubApiWorkerRuntimeEnv): ConfigResult<HubApiWorkerRuntimeConfig> {
  return flatMapConfigResult(readRequiredRuntimeString(env, "HUNSU_HUB_ORIGIN_NAME"), originName =>
    mapConfigResult(readOptionalRuntimeUrl(env, "HUNSU_HUB_PUBLIC_API_URL"), publicHubApiUrl => ({
      originName,
      publicHubApiUrl,
      adminToken: readOptionalRuntimeString(env, "HUNSU_HUB_ADMIN_TOKEN")
    }))
  );
}

export function renderHubWranglerToml(config: HubCloudflareConfig): string {
  const lines = [
    "# Generated by @hunsu/config/cloudflare. Do not edit by hand.",
    `name = ${tomlString(config.workerName)}`,
    `main = ${tomlString(config.workerMain)}`,
    `compatibility_date = ${tomlString(config.compatibilityDate)}`,
    `compatibility_flags = [${config.compatibilityFlags.map(tomlString).join(", ")}]`,
    "",
    "[vars]",
    `HUNSU_HUB_ORIGIN_NAME = ${tomlString(config.originName)}`,
    `HUNSU_HUB_PUBLIC_API_URL = ${tomlString(config.publicHubApiUrl)}`,
    "",
    "[[d1_databases]]",
    `binding = ${tomlString("HUB_DB")}`,
    `database_name = ${tomlString(config.d1DatabaseName)}`,
    `database_id = ${tomlString(config.d1DatabaseId)}`,
    `migrations_dir = ${tomlString("../migrations")}`,
    "",
    "[[r2_buckets]]",
    `binding = ${tomlString("HUB_PACKAGES")}`,
    `bucket_name = ${tomlString(config.r2BucketName)}`
  ];

  if (config.publishQueueName) {
    lines.push(
      "",
      "[[queues.producers]]",
      `binding = ${tomlString("HUB_PUBLISH_QUEUE")}`,
      `queue = ${tomlString(config.publishQueueName)}`
    );
  }

  return `${lines.join("\n")}\n`;
}

function ok<T>(value: T): ConfigResult<T> {
  return { ok: true, value };
}

function err(error: CloudflareConfigError): ConfigResult<never> {
  return { ok: false, error };
}

function mapConfigResult<T, U>(result: ConfigResult<T>, transform: (value: T) => U): ConfigResult<U> {
  return result.ok ? ok(transform(result.value)) : result;
}

function flatMapConfigResult<T, U>(result: ConfigResult<T>, transform: (value: T) => ConfigResult<U>): ConfigResult<U> {
  return result.ok ? transform(result.value) : result;
}

function readDeployTarget(env: Env): ConfigResult<HunsuDeployTarget> {
  const raw = readOptionalString(env, "HUNSU_DEPLOY_TARGET") ?? "local";
  if (isDeployTarget(raw)) {
    return ok(raw);
  }
  return err({
    code: "invalid_enum",
    env: "HUNSU_DEPLOY_TARGET",
    value: raw,
    allowed: HUNSU_DEPLOY_TARGETS,
    message: `Invalid HUNSU_DEPLOY_TARGET: ${raw}. Expected one of: ${HUNSU_DEPLOY_TARGETS.join(", ")}.`
  });
}

function isDeployTarget(value: string): value is HunsuDeployTarget {
  return (HUNSU_DEPLOY_TARGETS as readonly string[]).includes(value);
}

function readRequiredString(env: Env, envName: keyof typeof LOCAL_HUB_DEFAULTS, target: HunsuDeployTarget): ConfigResult<string> {
  const raw = readOptionalString(env, envName) ?? (target === "local" ? LOCAL_HUB_DEFAULTS[envName] : undefined);
  if (raw) {
    return ok(raw);
  }
  return missing(envName);
}

function readRequiredUrl(env: Env, envName: "HUNSU_HUB_PUBLIC_API_URL", target: HunsuDeployTarget): ConfigResult<string> {
  const raw = readOptionalString(env, envName) ?? (target === "local" ? LOCAL_HUB_DEFAULTS[envName] : undefined);
  if (!raw) {
    return missing(envName);
  }
  return validateUrl(raw, envName);
}

function readRequiredRuntimeString(env: HubApiWorkerRuntimeEnv, envName: "HUNSU_HUB_ORIGIN_NAME"): ConfigResult<string> {
  const raw = readOptionalRuntimeString(env, envName);
  if (raw) {
    return ok(raw);
  }
  return missing(envName);
}

function readOptionalRuntimeUrl(env: HubApiWorkerRuntimeEnv, envName: "HUNSU_HUB_PUBLIC_API_URL"): ConfigResult<string | undefined> {
  const raw = readOptionalRuntimeString(env, envName);
  return raw === undefined ? ok(undefined) : validateUrl(raw, envName);
}

function readOptionalString(env: Env, envName: string): string | undefined {
  const raw = env[envName];
  const trimmed = raw?.trim();
  return trimmed ? trimmed : undefined;
}

function readOptionalRuntimeString(env: HubApiWorkerRuntimeEnv, envName: keyof HubApiWorkerRuntimeEnv): string | undefined {
  const raw = env[envName];
  const trimmed = raw?.trim();
  return trimmed ? trimmed : undefined;
}

function validateUrl(value: string, envName: string): ConfigResult<string> {
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new Error("Unsupported protocol");
    }
    return ok(url.toString().replace(/\/$/, ""));
  } catch {
    return err({
      code: "invalid_url",
      env: envName,
      value,
      message: `Invalid ${envName}: ${value}. Expected an http or https URL.`
    });
  }
}

function missing(envName: string): ConfigResult<never> {
  return err({
    code: "missing_required_env",
    env: envName,
    message: `Missing required ${envName}.`
  });
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}
