export const GRAPH_NODE_WIDTH = 184;
export const GRAPH_NODE_HEIGHT = 112;
export const GRAPH_EDGE_LABEL_MAX_WIDTH = 180;
export const GRAPH_EDGE_LABEL_CLEARANCE = 20;
export const GRAPH_RUN_GAP =
  GRAPH_NODE_WIDTH + GRAPH_EDGE_LABEL_MAX_WIDTH + GRAPH_EDGE_LABEL_CLEARANCE * 2;
export const GRAPH_COACHING_GAP = 196;
